//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ThamGiaDuAn
    {
        public int MaNV { get; set; }
        public int MaDuAn { get; set; }
        public Nullable<System.DateTime> NgayThamGia { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_DuAn tbl_DuAn { get; set; }
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
