//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NhanVien()
        {
            this.tbl_ThamGiaDuAn = new HashSet<tbl_ThamGiaDuAn>();
            this.tbl_NhanVienThamGiaCongViec = new HashSet<tbl_NhanVienThamGiaCongViec>();
        }
    
        public int MaNV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    
        public virtual tbl_ChucVu tbl_ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ThamGiaDuAn> tbl_ThamGiaDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NhanVienThamGiaCongViec> tbl_NhanVienThamGiaCongViec { get; set; }
    }
}
