//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NhanVienThamGiaCongViec
    {
        public int MaCongViec { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> isManager { get; set; }
    
        public virtual tbl_CongViec tbl_CongViec { get; set; }
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
