//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DuAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DuAn()
        {
            this.tbl_GhiChuDuAn = new HashSet<tbl_GhiChuDuAn>();
            this.tbl_ThamGiaDuAn = new HashSet<tbl_ThamGiaDuAn>();
            this.tbl_CongViec = new HashSet<tbl_CongViec>();
        }
    
        public int MaDuAn { get; set; }
        public string TenDuAn { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<decimal> KinhPhi { get; set; }
        public Nullable<int> ThoiGianDuKien { get; set; }
        public Nullable<System.DateTime> NgayKhoiCong { get; set; }
        public Nullable<bool> TrangThaiDuAn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GhiChuDuAn> tbl_GhiChuDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ThamGiaDuAn> tbl_ThamGiaDuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CongViec> tbl_CongViec { get; set; }
    }
}
