//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CongViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CongViec()
        {
            this.tbl_NhanVienThamGiaCongViec = new HashSet<tbl_NhanVienThamGiaCongViec>();
        }
    
        public int MaCongViec { get; set; }
        public Nullable<int> MaDuAn { get; set; }
        public string MucTieu { get; set; }
        public Nullable<double> ThoiGianHoanThanh { get; set; }
        public string ChiThietCongViec { get; set; }
        public Nullable<double> TienDo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual tbl_DuAn tbl_DuAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NhanVienThamGiaCongViec> tbl_NhanVienThamGiaCongViec { get; set; }
    }
}
